package game.client.module.ui.skill.skin
{

	/*
	SkillPanel:Container
		close:Button
		dragBar:DragBar
		tabs:RadioButtonGroup
		skill:Container
			annioux2rf1:Button
			anniouxx:Button
			anniouxx1:Button
			anniouxx2:Button
			annioux2rf:Button
			currentCultivationTxt:Label
			currentMoneyTxt:Label
			moneyBg:Image
			intxxdss1:Image
			intxxdss1:Image
			biaoti:Image
			upgrateneed:Image
			cultivationTxt:Label
			levelTxt:Label
			moneyTxt:Label
			nextLevelEffect:Label
			skillEffect:Label
			guildMember:List
			page:Stepper
			youkuang1:Image
			zoukuang1:Image
		jineng:Image
		taitou:Image
		kuangxxx1:Image
		xiakuang:Image
		henxian:Image
		hengxia2:Image
		waikuang:Image
		sa3:Image
		d2:Image
		kuang11111xas:Image
	*/
	public class SkillPanelSkin
	{
		public static var skin:Object=
			{name:"SkillPanel",type:"Container",x:0,y:0,width:431,height:595,
				children:
				[
					{name:"close",type:"Button",x:386,y:19,width:38,height:39,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:38,height:39,
								normal:{link:"SkillPanel.guanbi",x:0,y:0,width:38,height:39},
								over:{link:"SkillPanel.guanbijingguo",x:0,y:0,width:38,height:39},
								down:{link:"SkillPanel.guanbianxia",x:0,y:0,width:38,height:39}
							}
						]
					},
					{name:"dragBar",type:"DragBar",x:0,y:0,width:390,height:46},
					{name:"tabs",type:"RadioButtonGroup",x:7,y:46,width:250,height:47,
						children:
						[
							{name:"ti3",type:"RadioButton",x:166,y:0,width:84,height:47,
								children:
								[
									{name:"txtbanghuiqishu",type:"Label",x:12,y:13,width:60,height:20,
										normal:{x:0,y:0,width:60,height:20,content:"<font color='#838383'>帮会奇术</font>",format:{align:"center",bold:false,color:0x838383,font:"SimSun",italic:false,leading:18,letterSpacing:0,size:14,underline:false}}
									},
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:84,height:47,top:4,right:4,bottom:4,left:4,
										normal:{link:"SkillPanel.tabpingshi",x:1,y:0,width:44,height:39},
										over:{link:"SkillPanel.tabjingguo",x:0,y:0,width:83,height:39},
										down:{link:"SkillPanel.tabanxia",x:0,y:0,width:84,height:47}
									}
								]
							},
							{name:"ti2",type:"RadioButton",x:83,y:0,width:84,height:47,
								children:
								[
									{name:"txtbeidongjinegn",type:"Label",x:12,y:13,width:60,height:20,
										normal:{x:0,y:0,width:60,height:20,content:"<font color='#838383'>被动技能</font>",format:{align:"center",bold:false,color:0x838383,font:"SimSun",italic:false,leading:18,letterSpacing:0,size:14,underline:false}}
									},
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:84,height:47,top:4,right:4,bottom:4,left:4,
										normal:{link:"SkillPanel.tabpingshi",x:1,y:0,width:44,height:39},
										over:{link:"SkillPanel.tabjingguo",x:0,y:0,width:83,height:39},
										down:{link:"SkillPanel.tabanxia",x:0,y:0,width:84,height:47}
									}
								]
							},
							{name:"ti1",type:"RadioButton",x:0,y:0,width:84,height:47,
								children:
								[
									{name:"txtzhudongjineng",type:"Label",x:12,y:13,width:60,height:20,
										normal:{x:0,y:0,width:60,height:20,content:"<font color='#838383'>主动技能</font>",format:{align:"center",bold:false,color:0x838383,font:"SimSun",italic:false,leading:18,letterSpacing:0,size:14,underline:false}}
									},
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:84,height:47,top:4,right:4,bottom:4,left:4,
										normal:{link:"SkillPanel.tabpingshi",x:1,y:0,width:44,height:39},
										over:{link:"SkillPanel.tabjingguo",x:0,y:0,width:83,height:39},
										down:{link:"SkillPanel.tabanxia",x:0,y:0,width:84,height:47}
									}
								]
							}
						]
					},
					{name:"skill",type:"Container",x:27,y:107,width:378,height:455,
						children:
						[
							{name:"annioux2rf1",type:"Button",x:351,y:429,width:23,height:24,
								children:
								[
									{name:"myImage",type:"Image",x:0,y:0,width:23,height:24,
										normal:{link:"SkillPanel.sdsfdfsdf",x:0,y:1,width:23,height:23},
										down:{link:"SkillPanel.sdsfdfsd2",x:0,y:0,width:23,height:23}
									}
								]
							},
							{name:"anniouxx",type:"Button",x:206,y:383,width:77,height:26,
								children:
								[
									{name:"txtzizi",type:"Label",x:12,y:6,width:52,height:17,
										normal:{x:0,y:0,width:52,height:17,content:"<font color='#ffffff'>一键升阶</font>",format:{align:"left",bold:false,color:0xffffff,font:"NSimSun",italic:false,leading:21,letterSpacing:0,size:12,underline:false}}
									},
									{name:"myImage",type:"Image",x:0,y:0,width:77,height:26,
										normal:{link:"SkillPanel.anniouxx",x:0,y:0,width:76,height:26},
										over:{link:"SkillPanel.jishoudi1",x:1,y:0,width:76,height:26},
										down:{link:"SkillPanel.jishoudi2",x:1,y:0,width:76,height:26}
									}
								]
							},
							{name:"anniouxx1",type:"Button",x:288,y:383,width:77,height:26,
								children:
								[
									{name:"textStudy",type:"Label",x:12,y:6,width:52,height:17,
										normal:{x:0,y:0,width:52,height:17,content:"<font color='#ffffff'>学习技能</font>",format:{align:"left",bold:false,color:0xffffff,font:"NSimSun",italic:false,leading:21,letterSpacing:0,size:12,underline:false}}
									},
									{name:"myImage",type:"Image",x:0,y:0,width:77,height:26,
										normal:{link:"SkillPanel.anniouxx2",x:0,y:0,width:76,height:26},
										over:{link:"SkillPanel.jishoudi1",x:1,y:0,width:76,height:26},
										down:{link:"SkillPanel.jishoudi2",x:1,y:0,width:76,height:26}
									}
								]
							},
							{name:"anniouxx2",type:"Button",x:288,y:383,width:77,height:26,
								children:
								[
									{name:"txtzizi2",type:"Label",x:12,y:6,width:52,height:17,
										normal:{x:0,y:0,width:52,height:17,content:"<font color='#ffffff'>升阶技能</font>",format:{align:"left",bold:false,color:0xffffff,font:"NSimSun",italic:false,leading:21,letterSpacing:0,size:12,underline:false}}
									},
									{name:"myImage",type:"Image",x:0,y:0,width:77,height:26,
										normal:{link:"SkillPanel.anniouxx2",x:0,y:0,width:76,height:26},
										over:{link:"SkillPanel.jishoudi1",x:1,y:0,width:76,height:26},
										down:{link:"SkillPanel.jishoudi2",x:1,y:0,width:76,height:26}
									}
								]
							},
							{name:"annioux2rf",type:"Button",x:188,y:429,width:23,height:24,
								children:
								[
									{name:"myImage",type:"Image",x:0,y:0,width:23,height:24,
										normal:{link:"SkillPanel.sdsfdfsdf",x:0,y:1,width:23,height:23},
										over:{link:"SkillPanel.sdsfdfsdf1",x:0,y:1,width:23,height:23},
										down:{link:"SkillPanel.sdsfdfsd2",x:0,y:0,width:23,height:23}
									}
								]
							},
							{name:"currentCultivationTxt",type:"Label",x:282,y:434,width:28,height:17,
								normal:{x:0,y:0,width:28,height:17,content:"<font color='#ffffff'>4545</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"currentMoneyTxt",type:"Label",x:119,y:434,width:28,height:17,
								normal:{x:0,y:0,width:28,height:17,content:"<font color='#ffffff'>4545</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"moneyBg",type:"Image",x:57,y:434,width:216,height:14,
								normal:{link:"SkillPanel.moneyBg",x:0,y:0,width:216,height:14}
							},
							{name:"intxxdss1",type:"Image",x:275,y:428,width:75,height:27,
								normal:{link:"SkillPanel.intxxdss1",x:0,y:0,width:75,height:27}
							},
							{name:"intxxdss1",type:"Image",x:112,y:428,width:75,height:27,
								normal:{link:"SkillPanel.intxxdss1",x:0,y:0,width:75,height:27}
							},
							{name:"biaoti",type:"Image",x:194,y:6,width:183,height:309,
								normal:{link:"SkillPanel.biaoti",x:0,y:0,width:183,height:309}
							},
							{name:"upgrateneed",type:"Image",x:206,y:313,width:48,height:61,
								normal:{link:"SkillPanel.upgrateneed",x:0,y:0,width:48,height:61}
							},
							{name:"cultivationTxt",type:"Label",x:244,y:352,width:10,height:17,
								normal:{x:0,y:0,width:10,height:17,content:"<font color='#ffffff'>0</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"levelTxt",type:"Label",x:244,y:312,width:10,height:17,
								normal:{x:0,y:0,width:10,height:17,content:"<font color='#ffffff'>0</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"moneyTxt",type:"Label",x:244,y:332,width:10,height:17,
								normal:{x:0,y:0,width:10,height:17,content:"<font color='#ffffff'>0</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"nextLevelEffect",type:"Label",x:205,y:177,width:82,height:17,
								normal:{x:0,y:0,width:82,height:17,content:"<font color='#7cd2e1'>冷却限制：</font><font color='#ffffff'>200</font>",format:{align:"left",bold:false,color:0x7cd2e1,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"skillEffect",type:"Label",x:205,y:32,width:82,height:17,
								normal:{x:0,y:0,width:82,height:17,content:"<font color='#7cd2e1'>冷却限制：</font><font color='#ffffff'>200</font>",format:{align:"left",bold:false,color:0x7cd2e1,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
							},
							{name:"guildMember",type:"List",x:11,y:21,width:75,height:95,
								item:
									{name:"myItem",type:"Container",x:0,y:0,width:75,height:95,
									children:
									[
										{name:"txtdang",type:"Label",x:9,y:69,width:16,height:17,
											normal:{x:0,y:0,width:16,height:17,content:"<font color='#ffffff'>单</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:2.4,letterSpacing:0,size:12,underline:false}}
										},
										{name:"txtshuzi",type:"Label",x:9,y:30,width:12,height:19,
											normal:{x:0,y:0,width:12,height:19,content:"<font color='#ffffff'>9</font>",format:{align:"left",bold:false,color:0xffffff,font:"Verdana",italic:false,leading:2.4,letterSpacing:0,size:12,underline:false}}
										},
										{name:"txthuofeng",type:"Label",x:12,y:7,width:52,height:17,
											normal:{x:0,y:0,width:52,height:17,content:"<font color='#ffffff'>普通攻击</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:2.4,letterSpacing:0,size:12,underline:false}}
										},
										{name:"beijingxing",type:"Image",x:0,y:0,width:75,height:95,
											normal:{link:"SkillPanel.beijingxing",x:0,y:0,width:75,height:95}
										}
									]
								},
								children:
								[

								]
							},
							{name:"page",type:"Stepper",x:42,y:362,width:99,height:27,
								children:
								[
									{name:"txt",type:"Label",x:39,y:6,width:22,height:17,
										normal:{x:0,y:0,width:22,height:17,content:"<font color='#ffffff'>1/2</font>",format:{align:"center",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
									},
									{name:"shurukuangdiban",type:"Image",x:22,y:0,width:55,height:27,
										normal:{link:"SkillPanel.shurukuangdiban",x:0,y:0,width:55,height:27}
									},
									{name:"nextBtn",type:"Button",x:76,y:2,width:23,height:23,
										children:
										[
											{name:"xiangyou",type:"Image",x:7,y:6,width:10,height:11,
												normal:{link:"SkillPanel.xiangyou",x:0,y:0,width:10,height:11}
											},
											{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:23,height:23,top:4,right:4,bottom:4,left:4,
												normal:{link:"SkillPanel.zuoyoudi",x:0,y:0,width:23,height:23},
												over:{link:"SkillPanel.zuoyoudia",x:0,y:0,width:23,height:23},
												down:{link:"SkillPanel.zuoyoudi",x:0,y:0,width:23,height:23}
											}
										]
									},
									{name:"prevBtn",type:"Button",x:0,y:2,width:23,height:23,
										children:
										[
											{name:"zuoJiantou",type:"Image",x:6,y:6,width:10,height:11,
												normal:{link:"SkillPanel.zuoJiantou",x:0,y:0,width:10,height:11}
											},
											{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:23,height:23,top:4,right:4,bottom:4,left:4,
												normal:{link:"SkillPanel.xiangzuo",x:0,y:0,width:23,height:23},
												over:{link:"SkillPanel.zuoss",x:0,y:0,width:23,height:23},
												down:{link:"SkillPanel.zuosss",x:0,y:0,width:23,height:23}
											}
										]
									}
								]
							},
							{name:"youkuang1",type:"Image",x:193,y:0,width:185,height:420,
								normal:{link:"SkillPanel.youkuang1",x:0,y:0,width:185,height:420}
							},
							{name:"zoukuang1",type:"Image",x:0,y:0,width:185,height:420,
								normal:{link:"SkillPanel.zoukuang1",x:0,y:0,width:185,height:420}
							}
						]
					},
					{name:"jineng",type:"Image",x:190,y:17,width:49,height:27,
						normal:{link:"SkillPanel.jineng",x:0,y:0,width:49,height:27}
					},
					{name:"taitou",type:"Image",x:0,y:0,width:430,height:86,
						normal:{link:"SkillPanel.taitou",x:0,y:0,width:430,height:86}
					},
					{name:"kuangxxx1",type:"Image",x:14,y:93,width:403,height:484,
						normal:{link:"SkillPanel.kuangxxx1",x:0,y:0,width:403,height:484}
					},
					{name:"xiakuang",type:"Image",x:1,y:572,width:430,height:23,
						normal:{link:"SkillPanel.xiakuang",x:0,y:0,width:430,height:23}
					},
					{name:"henxian",type:"Image",x:9,y:86,width:413,height:3,
						normal:{link:"SkillPanel.henxian",x:0,y:0,width:413,height:3}
					},
					{name:"hengxia2",type:"Image",x:9,y:89,width:413,height:12,
						normal:{link:"SkillPanel.hengxia2",x:0,y:0,width:413,height:12}
					},
					{name:"waikuang",type:"Image",x:6,y:16,width:420,height:569,
						normal:{link:"SkillPanel.waikuang",x:0,y:0,width:420,height:569}
					},
					{name:"sa3",type:"Image",x:8,y:45,width:415,height:35,
						normal:{link:"SkillPanel.sa3",x:0,y:0,width:415,height:35}
					},
					{name:"d2",type:"Image",x:7,y:50,width:416,height:16,
						normal:{link:"SkillPanel.d2",x:0,y:0,width:416,height:16}
					},
					{name:"kuang11111xas",type:"Image",x:7,y:19,width:416,height:572,
						normal:{link:"SkillPanel.kuang11111xas",x:0,y:0,width:416,height:572}
					}
				]
			};
	}
}