package game.client.module.ui.chat.skin
{

	/*
	ChatPanel:Container
		tabs:RadioButtonGroup
		pinbi:Button
		expansion:Button
		xiaolian:Button
		xin:Button
		channal:Button
		huiche:Button
		msgScroll:ScrollBar
		txtwanjiaming:Label
		anke:Image
		liaotiankuang:Image
	*/
	public class ChatPanelSkin
	{
		public static var skin:Object=
			{name:"ChatPanel",type:"Container",x:0,y:0,width:331,height:231,
				children:
				[
					{name:"tabs",type:"RadioButtonGroup",x:0,y:168,width:272,height:18,
						children:
						[
							{name:"speaker",type:"RadioButton",x:234,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.chat1",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.chat",x:0,y:0,width:38,height:18}
									}
								]
							},
							{name:"team",type:"RadioButton",x:195,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.zudui1",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.zudui",x:0,y:0,width:38,height:18}
									}
								]
							},
							{name:"guild",type:"RadioButton",x:156,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.guild1",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.guild",x:0,y:0,width:38,height:18}
									}
								]
							},
							{name:"camp",type:"RadioButton",x:117,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.camp1",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.camp",x:0,y:0,width:38,height:18}
									}
								]
							},
							{name:"scene",type:"RadioButton",x:78,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.scene1",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.scene",x:0,y:0,width:38,height:18}
									}
								]
							},
							{name:"world",type:"RadioButton",x:39,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.zonghe2",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.zonghe",x:0,y:0,width:38,height:18}
									}
								]
							},
							{name:"all",type:"RadioButton",x:0,y:0,width:38,height:18,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:38,height:18,top:4,right:4,bottom:4,left:4,
										normal:{link:"ChatPanel.all1",x:0,y:0,width:38,height:18},
										down:{link:"ChatPanel.all",x:0,y:0,width:38,height:18}
									}
								]
							}
						]
					},
					{name:"pinbi",type:"Button",x:273,y:168,width:27,height:18,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:27,height:18,
								normal:{link:"ChatPanel.ding1",x:0,y:0,width:27,height:18},
								down:{link:"ChatPanel.ding",x:0,y:0,width:27,height:18}
							}
						]
					},
					{name:"expansion",type:"Button",x:301,y:168,width:27,height:18,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:27,height:18,
								normal:{link:"ChatPanel.jiantou1",x:0,y:0,width:27,height:18},
								down:{link:"ChatPanel.jiantou",x:0,y:0,width:27,height:18}
							}
						]
					},
					{name:"xiaolian",type:"Button",x:281,y:195,width:12,height:12,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:12,height:12,
								normal:{link:"ChatPanel.haha",x:0,y:0,width:12,height:12},
								over:{link:"ChatPanel.haha1",x:0,y:0,width:12,height:12},
								down:{link:"ChatPanel.haha2",x:0,y:0,width:12,height:12}
							}
						]
					},
					{name:"xin",type:"Button",x:305,y:196,width:12,height:11,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:12,height:11,
								normal:{link:"ChatPanel.xin",x:0,y:0,width:12,height:11},
								over:{link:"ChatPanel.xin1",x:0,y:0,width:12,height:11},
								down:{link:"ChatPanel.xin2",x:0,y:0,width:12,height:11}
							}
						]
					},
					{name:"channal",type:"Button",x:17,y:197,width:32,height:26,
						children:
						[
							{name:"Label",type:"Label",x:0,y:6,width:32,height:20,
								normal:{x:0,y:0,width:32,height:20,content:"<font color='#ffffff'>帮会</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:14,underline:false}}
							},
							{name:"myImage",type:"Image",x:9,y:0,width:9,height:6,
								normal:{link:"ChatPanel.shang",x:0,y:0,width:9,height:6},
								over:{link:"ChatPanel.shang1",x:0,y:0,width:9,height:6},
								down:{link:"ChatPanel.shang2",x:0,y:0,width:9,height:6}
							}
						]
					},
					{name:"huiche",type:"Button",x:274,y:209,width:52,height:15,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:52,height:15,
								normal:{link:"ChatPanel.huiche",x:0,y:0,width:52,height:15},
								over:{link:"ChatPanel.huiche1",x:0,y:0,width:52,height:15},
								down:{link:"ChatPanel.huiche2",x:0,y:0,width:52,height:15}
							}
						]
					},
					{name:"msgScroll",type:"ScrollBar",x:0,y:2,width:19,height:164,
						children:
						[
							{name:"arrowDown",type:"Button",x:0,y:146,width:18,height:18,
								children:
								[
									{name:"myImage",type:"Image",x:0,y:0,width:18,height:18,
										normal:{link:"ChatPanel.rwzuizong18",x:0,y:0,width:18,height:18},
										over:{link:"ChatPanel.rwzuizong18x",x:0,y:0,width:18,height:18},
										down:{link:"ChatPanel.rwzuizong18xx",x:0,y:0,width:18,height:18}
									}
								]
							},
							{name:"arrowUp",type:"Button",x:1,y:0,width:18,height:17,
								children:
								[
									{name:"myImage",type:"Image",x:0,y:0,width:18,height:17,
										normal:{link:"ChatPanel.rwzuizong4",x:0,y:0,width:18,height:17},
										over:{link:"ChatPanel.rwzuizong4x",x:0,y:0,width:18,height:17},
										down:{link:"ChatPanel.rwzuizong4xx",x:0,y:0,width:18,height:17}
									}
								]
							},
							{name:"thumb",type:"Button",x:2,y:19,width:16,height:38,
								children:
								[
									{name:"back",type:"ScaleImage",x:0,y:0,width:16,height:38,top:10,right:5,bottom:10,left:5,
										normal:{link:"ChatPanel.rwzuizong5xx",x:0,y:0,width:16,height:38},
										over:{link:"ChatPanel.rwzuizong5xxx",x:0,y:0,width:16,height:38},
										down:{link:"ChatPanel.rwzuizong5xxxx",x:0,y:0,width:16,height:38}
									}
								]
							},
							{name:"track",type:"Button",x:1,y:17,width:18,height:129,
								children:
								[
									{name:"track",type:"ScaleImage",x:0,y:0,width:18,height:129,top:10,right:5,bottom:10,left:5,
										normal:{link:"ChatPanel.track",x:0,y:0,width:18,height:129}
									}
								]
							}
						]
					},
					{name:"txtwanjiaming",type:"Label",x:63,y:195,width:208,height:30,
						normal:{x:0,y:0,width:208,height:30,content:"<font color='#65ff65'>有没有公会收入啊，50级的小刺客，在线时间绝对可以保证。</font>",format:{align:"left",bold:false,color:0x65ff65,font:"SimSun",italic:false,leading:1,letterSpacing:0,size:12,underline:false}}
					},
					{name:"anke",type:"Image",x:0,y:189,width:331,height:42,
						normal:{link:"ChatPanel.anke",x:0,y:0,width:331,height:42}
					},
					{name:"liaotiankuang",type:"Image",x:0,y:0,width:331,height:188,
						normal:{link:"ChatPanel.liaotiankuang",x:0,y:0,width:331,height:188}
					}
				]
			};
	}
}