package game.client.module.ui.mainMenu.skin
{

	/*
	MainMenuPanel:Container
		zuoqi:Button
		chibang:Button
		taobao:Button
		lianqi:Button
		baoshi:Button
		zhizuo:Button
		zhanting:Button
		dazuo:Button
		qicheng:Button
		qinggong:Button
		youbiao:Button
		youbiaob:Button
		jian:Button
		jia:Button
		jiaose:Button
		beibao:Button
		jineng:Button
		shenhun:Button
		wujiang:Button
		banghui:Button
		haoyou:Button
		shichang:Button
		shangcheng:Button
		txtjingyanzhi:Label
		skillMenu:Container
			txt8:Label
			txt7:Label
			txt6:Label
			txt5:Label
			txt4:Label
			txt3:Label
			txt2:Label
			txt1:Label
			kuang1:Image
		gezisad:Image
		geziawa:Image
		gezisergwe:Image
		geziswe:Image
		geziswefw3e:Image
		gezisgerh:Image
		gezisrg:Image
		gezioo:Image
		gezif:Image
		gege:Image
		jingyantiao:Image
		circle0:Container
			nuqidianlc:Image
			nuqidianl:Image
		circle1:Container
			nuqidianhc:Image
			nuqidianh:Image
		circle2:Container
			nuqidiandc:Image
			nuqidiand:Image
		circle3:Container
			nuqidiancb:Image
			nuqidianc:Image
		circle4:Container
			nuqidiangc:Image
			nuqidiang:Image
		circle5:Container
			nuqidiankb:Image
			nuqidiank:Image
		nu:Image
		dishang:Image
		xuetiao:Image
		mofa:Image
		di:Image
	*/
	public class MainMenuPanelSkin
	{
		public static var skin:Object=
			{name:"MainMenuPanel",type:"Container",x:0,y:0,width:898,height:128,
				children:
				[
					{name:"zuoqi",type:"Button",x:644,y:25,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.zuoqi",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.zuoqib",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.zuoqic",x:0,y:0,width:34,height:42}
							}
						]
					},
					{name:"chibang",type:"Button",x:682,y:25,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.zhibagn",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.zhibagnc",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.zhibagnd",x:0,y:0,width:34,height:42}
							}
						]
					},
					{name:"taobao",type:"Button",x:833,y:25,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.taobao",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.taboab",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.taobaoc",x:0,y:0,width:34,height:42}
							}
						]
					},
					{name:"lianqi",type:"Button",x:719,y:25,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.lianqi",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.lianqix",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.lianqiz",x:0,y:0,width:34,height:42}
							}
						]
					},
					{name:"baoshi",type:"Button",x:795,y:25,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.chfbang",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.baoshib",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.baoshic",x:0,y:0,width:34,height:42}
							}
						]
					},
					{name:"zhizuo",type:"Button",x:757,y:25,width:34,height:41,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:41,
								normal:{link:"MainMenuPanel.zhizuozhibagn",x:0,y:0,width:34,height:40},
								over:{link:"MainMenuPanel.zhizuob",x:0,y:0,width:34,height:40},
								down:{link:"MainMenuPanel.zhizuoc",x:0,y:0,width:34,height:41}
							}
						]
					},
					{name:"zhanting",type:"Button",x:335,y:24,width:34,height:41,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:41,
								normal:{link:"MainMenuPanel.guaji",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.guaji1",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.guaji2",x:0,y:0,width:34,height:41},
								disable:{link:"MainMenuPanel.guaji3",x:0,y:0,width:34,height:41}
							}
						]
					},
					{name:"dazuo",type:"Button",x:296,y:24,width:34,height:41,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:41,
								normal:{link:"MainMenuPanel.dazuo",x:0,y:0,width:34,height:40},
								over:{link:"MainMenuPanel.dazuob",x:0,y:0,width:34,height:40},
								down:{link:"MainMenuPanel.dazuoc",x:0,y:0,width:34,height:41}
							}
						]
					},
					{name:"qicheng",type:"Button",x:257,y:24,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.qicheng",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.qichengb",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.qichegnc",x:0,y:0,width:34,height:42}
							}
						]
					},
					{name:"qinggong",type:"Button",x:217,y:24,width:34,height:42,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:34,height:42,
								normal:{link:"MainMenuPanel.qinggogn",x:0,y:0,width:34,height:41},
								over:{link:"MainMenuPanel.qigngognb",x:0,y:0,width:34,height:41},
								down:{link:"MainMenuPanel.qinggongc",x:0,y:0,width:34,height:42},
								disable:{link:"MainMenuPanel.qinggognd",x:0,y:0,width:34,height:41}
							}
						]
					},
					{name:"youbiao",type:"Button",x:446,y:10,width:9,height:25,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:9,height:25,
								normal:{link:"MainMenuPanel.youbiao",x:0,y:0,width:9,height:25}
							}
						]
					},
					{name:"youbiaob",type:"Button",x:446,y:10,width:9,height:25,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:9,height:25,
								normal:{link:"MainMenuPanel.youbiao",x:0,y:0,width:9,height:25}
							}
						]
					},
					{name:"jian",type:"Button",x:408,y:92,width:24,height:24,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:24,height:24,
								normal:{link:"MainMenuPanel.jiaxie",x:0,y:0,width:24,height:24},
								over:{link:"MainMenuPanel.jiaxieb",x:0,y:0,width:24,height:24},
								down:{link:"MainMenuPanel.jiaxiec",x:0,y:0,width:24,height:24}
							}
						]
					},
					{name:"jia",type:"Button",x:472,y:92,width:24,height:24,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:24,height:24,
								normal:{link:"MainMenuPanel.jialan",x:0,y:0,width:24,height:24},
								over:{link:"MainMenuPanel.jialanb",x:0,y:0,width:24,height:24},
								down:{link:"MainMenuPanel.jialanc",x:0,y:0,width:24,height:24}
							}
						]
					},
					{name:"jiaose",type:"Button",x:527,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.juese",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.jueseb",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.juesec",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"beibao",type:"Button",x:565,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.beibao",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.beibaob",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.beibaoc",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"jineng",type:"Button",x:603,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.jineng",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.jinengb",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.jinengc",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"shenhun",type:"Button",x:641,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.shenhun",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.shenhunb",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.shenhunc",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"wujiang",type:"Button",x:679,y:70,width:37,height:45,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:45,
								normal:{link:"MainMenuPanel.wujiang",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.wujiang1",x:0,y:0,width:37,height:43},
								down:{link:"MainMenuPanel.wujiang2",x:0,y:0,width:37,height:43},
								disable:{link:"MainMenuPanel.wujiang3",x:0,y:0,width:37,height:45}
							}
						]
					},
					{name:"banghui",type:"Button",x:717,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.bagnhui",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.bagnhuib",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.bagnhuic",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"haoyou",type:"Button",x:755,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.richang",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.richagnb",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.richagnc",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"shichang",type:"Button",x:793,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.shichagn",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.shichangb",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.shichangc",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"shangcheng",type:"Button",x:831,y:70,width:37,height:46,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:37,height:46,
								normal:{link:"MainMenuPanel.shagnchegn",x:0,y:0,width:37,height:45},
								over:{link:"MainMenuPanel.shangchengb",x:0,y:0,width:37,height:45},
								down:{link:"MainMenuPanel.shangchengc",x:0,y:0,width:37,height:46}
							}
						]
					},
					{name:"txtjingyanzhi",type:"Label",x:440,y:114,width:24,height:14,
						normal:{x:0,y:0,width:24,height:14,content:"<font color='#ffffff'>70%</font>",format:{align:"left",bold:false,color:0xffffff,font:"Tahoma",italic:false,leading:13.75,letterSpacing:0,size:9,underline:false}}
					},
					{name:"skillMenu",type:"Container",x:28,y:71,width:343,height:42,
						children:
						[
							{name:"txt8",type:"Label",x:305,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>8</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt7",type:"Label",x:262,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>7</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt6",type:"Label",x:219,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>6</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt5",type:"Label",x:176,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>5</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt4",type:"Label",x:133,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>4</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt3",type:"Label",x:90,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>3</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt2",type:"Label",x:47,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>2</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"txt1",type:"Label",x:4,y:4,width:9,height:15,
								normal:{x:0,y:0,width:9,height:15,content:"<font color='#ffffff'>1</font>",format:{align:"left",bold:false,color:0xffffff,font:"ArialMT",italic:false,leading:24,letterSpacing:0,size:9,underline:false}}
							},
							{name:"kuang1",type:"Image",x:0,y:0,width:343,height:42,
								normal:{link:"MainMenuPanel.kuang1",x:0,y:0,width:343,height:42}
							}
						]
					},
					{name:"gezisad",type:"Image",x:831,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.gezisad",x:0,y:0,width:37,height:43}
					},
					{name:"geziawa",type:"Image",x:793,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.geziawa",x:0,y:0,width:37,height:43}
					},
					{name:"gezisergwe",type:"Image",x:755,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.gezisergwe",x:0,y:0,width:37,height:43}
					},
					{name:"geziswe",type:"Image",x:717,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.geziswe",x:0,y:0,width:37,height:43}
					},
					{name:"geziswefw3e",type:"Image",x:679,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.geziswefw3e",x:0,y:0,width:37,height:43}
					},
					{name:"gezisgerh",type:"Image",x:641,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.gezisgerh",x:0,y:0,width:37,height:43}
					},
					{name:"gezisrg",type:"Image",x:565,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.gezisrg",x:0,y:0,width:37,height:43}
					},
					{name:"gezioo",type:"Image",x:527,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.gezioo",x:0,y:0,width:37,height:43}
					},
					{name:"gezif",type:"Image",x:603,y:70,width:37,height:43,
						normal:{link:"MainMenuPanel.gezif",x:0,y:0,width:37,height:43}
					},
					{name:"gege",type:"Image",x:71,y:114,width:760,height:13,
						normal:{link:"MainMenuPanel.gege",x:0,y:0,width:760,height:13}
					},
					{name:"jingyantiao",type:"Image",x:26,y:118,width:848,height:6,
						normal:{link:"MainMenuPanel.jingyantiao",x:0,y:0,width:848,height:6}
					},
					{name:"circle0",type:"Container",x:424,y:73,width:9,height:9,
						children:
						[
							{name:"nuqidianlc",type:"Image",x:0,y:3,width:9,height:6,
								normal:{link:"MainMenuPanel.nuqidianlc",x:0,y:0,width:9,height:6}
							},
							{name:"nuqidianl",type:"Image",x:0,y:0,width:9,height:9,
								normal:{link:"MainMenuPanel.nuqidianl",x:0,y:0,width:9,height:9}
							}
						]
					},
					{name:"circle1",type:"Container",x:427,y:57,width:9,height:9,
						children:
						[
							{name:"nuqidianhc",type:"Image",x:0,y:2,width:9,height:7,
								normal:{link:"MainMenuPanel.nuqidianhc",x:0,y:0,width:9,height:7}
							},
							{name:"nuqidianh",type:"Image",x:0,y:0,width:9,height:9,
								normal:{link:"MainMenuPanel.nuqidianh",x:0,y:0,width:9,height:9}
							}
						]
					},
					{name:"circle2",type:"Container",x:440,y:47,width:9,height:9,
						children:
						[
							{name:"nuqidiandc",type:"Image",x:0,y:0,width:6,height:9,
								normal:{link:"MainMenuPanel.nuqidiandc",x:0,y:0,width:6,height:9}
							},
							{name:"nuqidiand",type:"Image",x:0,y:0,width:9,height:9,
								normal:{link:"MainMenuPanel.nuqidiand",x:0,y:0,width:9,height:9}
							}
						]
					},
					{name:"circle3",type:"Container",x:455,y:47,width:9,height:9,
						children:
						[
							{name:"nuqidiancb",type:"Image",x:0,y:0,width:7,height:9,
								normal:{link:"MainMenuPanel.nuqidiancb",x:0,y:0,width:7,height:9}
							},
							{name:"nuqidianc",type:"Image",x:0,y:0,width:9,height:9,
								normal:{link:"MainMenuPanel.nuqidianc",x:0,y:0,width:9,height:9}
							}
						]
					},
					{name:"circle4",type:"Container",x:469,y:57,width:9,height:9,
						children:
						[
							{name:"nuqidiangc",type:"Image",x:0,y:0,width:9,height:7,
								normal:{link:"MainMenuPanel.nuqidiangc",x:0,y:0,width:9,height:7}
							},
							{name:"nuqidiang",type:"Image",x:0,y:0,width:9,height:9,
								normal:{link:"MainMenuPanel.nuqidiang",x:0,y:0,width:9,height:9}
							}
						]
					},
					{name:"circle5",type:"Container",x:472,y:73,width:9,height:9,
						children:
						[
							{name:"nuqidiankb",type:"Image",x:0,y:0,width:9,height:6,
								normal:{link:"MainMenuPanel.nuqidiankb",x:0,y:0,width:9,height:6}
							},
							{name:"nuqidiank",type:"Image",x:0,y:0,width:9,height:9,
								normal:{link:"MainMenuPanel.nuqidiank",x:0,y:0,width:9,height:9}
							}
						]
					},
					{name:"nu",type:"Image",x:420,y:43,width:65,height:53,
						normal:{link:"MainMenuPanel.nu",x:0,y:0,width:65,height:53}
					},
					{name:"dishang",type:"Image",x:24,y:0,width:853,height:128,
						normal:{link:"MainMenuPanel.dishang",x:0,y:0,width:853,height:128}
					},
					{name:"xuetiao",type:"Image",x:388,y:10,width:62,height:118,
						normal:{link:"MainMenuPanel.xuetiao",x:0,y:0,width:62,height:118}
					},
					{name:"mofa",type:"Image",x:450,y:10,width:63,height:118,
						normal:{link:"MainMenuPanel.mofa",x:0,y:0,width:63,height:118}
					},
					{name:"di",type:"Image",x:0,y:9,width:898,height:119,
						normal:{link:"MainMenuPanel.di",x:0,y:0,width:898,height:119}
					}
				]
			};
	}
}