package game.client.module.ui.rank.skin
{

	public class RankPanelSkin
	{
		public static var skin:Object=
			{name:"RankPanel",type:"Container",x:0,y:0,width:651,height:500,
				children:
				[
					{name:"waikuangd1",type:"Image",x:0,y:0,width:651,height:500,normal:{link:"shared.diban",x:0,y:0,width:651,height:500}},
					{name:"waikuangd2",type:"Image",x:9,y:31,width:633,height:460,normal:{link:"RankPanel_waikuangd2",x:0,y:0,width:633,height:460}},
					{name:"huawen",type:"Image",x:3,y:3,width:645,height:30,normal:{link:"RankPanel_huawen",x:0,y:0,width:645,height:30}},
					{name:"paihangming",type:"Image",x:317,y:6,width:53,height:25,normal:{link:"RankPanel_paihangming",x:0,y:0,width:53,height:25}},
					{name:"650x34",type:"DragBar",x:0,y:0,width:650,height:34},
					{name:"close",type:"Button",x:619,y:5,width:24,height:24,
						children:
						[
							{name:"myImage",type:"Image",x:0,y:0,width:24,height:24,normal:{link:"RankPanel_chahca",x:0,y:0,width:24,height:24}}
						]
					},
					{name:"hengxian",type:"Image",x:10,y:61,width:631,height:3,normal:{link:"RankPanel_hengxian",x:0,y:0,width:631,height:3}},
					{name:"tabs",type:"RadioButtonGroup",x:16,y:37,width:139,height:25,
						children:
						[
							{name:"qianghua",type:"RadioButton",x:0,y:0,width:69,height:25,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:69,height:24,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_paihangbangdi",x:0,y:0,width:69,height:24},down:{link:"RankPanel_paihangbangdier",x:0,y:0,width:69,height:24}},
									{name:"txtqianghua",type:"Label",x:15,y:7,width:42,height:17,content:"<font color='#ffffff'>排行榜</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
								]
							},
							{name:"zhuanbeixilian",type:"RadioButton",x:70,y:0,width:69,height:25,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:69,height:24,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_mingrentangdi",x:0,y:0,width:69,height:24},down:{link:"RankPanel_mingrentagndier",x:0,y:0,width:69,height:24}},
									{name:"txtxilian",type:"Label",x:14,y:7,width:42,height:17,content:"<font color='#ffffff'>战神界</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
								]
							}
						]
					},
					{name:"youkuang",type:"Image",x:17,y:103,width:112,height:350,normal:{link:"RankPanel_youkuang",x:0,y:0,width:112,height:350}},
					{name:"youkuang1",type:"Image",x:132,y:103,width:503,height:349,normal:{link:"RankPanel_youkuang1",x:0,y:0,width:503,height:349}},
					{name:"shangkuang",type:"Image",x:17,y:66,width:618,height:34,normal:{link:"RankPanel_shangkuang",x:0,y:0,width:618,height:34}},
					{name:"txtxingbie",type:"Label",x:493,y:76,width:41,height:17,content:"<font color='#ffffff'>性别：</font>",format:{align:"center",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:5,letterSpacing:-0.5,size:12,underline:false}},
					{name:"paimingguize",type:"Image",x:18,y:104,width:110,height:27,normal:{link:"RankPanel_paimingguize",x:0,y:0,width:110,height:27}},
					{name:"txtzhushi",type:"Label",x:453,y:461,width:180,height:17,content:"<font color='#ffffff'>连续7天不上线的玩家将撤销排名</font>",format:{align:"left",bold:false,color:0xffffff,font:"NSimSun",italic:false,leading:6,letterSpacing:0,size:12,underline:false}},
					{name:"txtzhushi1",type:"Label",x:140,y:461,width:138,height:17,content:"<font color='#ffffff'>每10分钟更新一次排行榜</font>",format:{align:"left",bold:false,color:0xffffff,font:"NSimSun",italic:false,leading:6,letterSpacing:0,size:12,underline:false}},
					{name:"xiaolei",type:"List",x:23,y:158,width:102,height:21,
						item:
							{name:"myItem",type:"Container",x:0,y:0,width:102,height:21,
							children:
							[
								{name:"hengxian",type:"Image",x:0,y:19,width:102,height:2,normal:{link:"RankPanel_hengxian",x:0,y:0,width:102,height:2}},
								{name:"zhandoupaihang",type:"Label",x:21,y:1,width:54,height:17,content:"<font color='#e5e3b5'>战斗排行</font>",format:{align:"left",bold:false,color:0xe5e3b5,font:"SimSun",italic:false,leading:10,letterSpacing:0,size:12,underline:false}},
								{name:"xuanzhogn",type:"Image",x:3,y:0,width:84,height:17,normal:{link:"RankPanel_xuanzhogn",x:0,y:0,width:84,height:17}}
							]
						},
						children:
						[

						]
					},
					{name:"dalei",type:"List",x:19,y:131,width:108,height:24,
						item:
							{name:"myItem",type:"Container",x:0,y:0,width:108,height:24,
							children:
							[
								{name:"gerenpaihang",type:"RadioButton",x:0,y:0,width:108,height:24,
									children:
									[
										{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:108,height:24,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_geren1",x:0,y:0,width:108,height:24},down:{link:"RankPanel_geren2",x:0,y:0,width:108,height:24}},
										{name:"txtgrph",type:"Label",
											normal:{x:29,y:3,width:54,height:17,content:"<font color='#fbff00'>个人排行</font>",format:{align:"left",bold:false,color:0xfbff00,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
										}
									]
								}
							]
						},
						children:
						[

						]
					},
					{name:"wodepaih",type:"Button",x:16,y:459,width:111,height:24,
						children:
						[
							{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:111,height:24,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_wodepim",x:0,y:0,width:111,height:24}},
							{name:"txtwodepaim",type:"Label",x:29,y:3,width:54,height:17,content:"<font color='#ffffff'>我的排名</font>",format:{align:"left",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}}
						]
					},
					{name:"fengexian1",type:"Image",x:61,y:76,width:93,height:16,normal:{link:"RankPanel_fengexian1",x:0,y:0,width:93,height:16}},
					{name:"fengexian2",type:"Image",x:567,y:76,width:36,height:16,normal:{link:"RankPanel_fengexian2",x:0,y:0,width:36,height:16}},
					{name:"wefwewer",type:"Image",x:357,y:458,width:58,height:22,normal:{link:"RankPanel_wefwewer",x:0,y:0,width:58,height:22}},
					{name:"txtPage",type:"Label",x:376,y:462,width:24,height:17,content:"<font color='#ffffff'>1/2</font>",format:{align:"center",bold:false,color:0xffffff,font:"SimSun",italic:false,leading:0,letterSpacing:0,size:12,underline:false}},
					{name:"xiangzuo",type:"Button",x:324,y:456,width:28,height:26,
						children:
						[
							{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:28,height:26,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_xiangzuo",x:0,y:0,width:28,height:26}},
							{name:"zuoJiantou",type:"Image",x:9,y:8,width:7,height:11,normal:{link:"RankPanel_zuoJiantou",x:0,y:0,width:7,height:11}}
						]
					},
					{name:"xiangyou",type:"Button",x:418,y:456,width:28,height:26,
						children:
						[
							{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:28,height:26,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_xiangyoudi",x:0,y:0,width:28,height:26}},
							{name:"xiangyou",type:"Image",x:12,y:8,width:7,height:11,normal:{link:"RankPanel_xiangyou",x:0,y:0,width:7,height:11}}
						]
					},
					{name:"zhiye",type:"RadioButtonGroup",x:22,y:73,width:171,height:23,
						children:
						[
							{name:"suoyou",type:"RadioButton",x:0,y:0,width:37,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:37,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_zhiye4",x:6,y:4,width:24,height:14},down:{link:"RankPanel_txtzhiyer4",x:0,y:0,width:37,height:23}}
								]
							},
							{name:"wusheng",type:"RadioButton",x:43,y:0,width:37,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:37,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_zhiye3",x:5,y:3,width:25,height:14},down:{link:"RankPanel_txtzhiye3",x:0,y:0,width:37,height:23}}
								]
							},
							{name:"xiaoyao",type:"RadioButton",x:89,y:0,width:37,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:37,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_zhiye2",x:6,y:4,width:25,height:14},down:{link:"RankPanel_txtzhiyer2",x:0,y:0,width:37,height:23}}
								]
							},
							{name:"shushi",type:"RadioButton",x:134,y:0,width:37,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:37,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_zhiye1",x:6,y:4,width:25,height:14},down:{link:"RankPanel_txtzhiyer1",x:0,y:0,width:37,height:23}}
								]
							}
						]
					},
					{name:"xingbie",type:"RadioButtonGroup",x:527,y:73,width:103,height:23,
						children:
						[
							{name:"suoyou",type:"RadioButton",x:0,y:0,width:37,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:37,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_xingbie3",x:5,y:4,width:25,height:14},down:{link:"RankPanel_txtxingbie3",x:0,y:0,width:37,height:23}}
								]
							},
							{name:"nan",type:"RadioButton",x:42,y:0,width:31,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:31,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_xingbie2",x:8,y:4,width:13,height:14},down:{link:"RankPanel_txtxingbie2",x:0,y:0,width:31,height:23}}
								]
							},
							{name:"nv",type:"RadioButton",x:80,y:0,width:23,height:23,
								children:
								[
									{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:23,height:23,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_xingbie1",x:5,y:4,width:13,height:14},down:{link:"RankPanel_txtxingbie1",x:0,y:0,width:23,height:23}}
								]
							}
						]
					},
					{name:"suozyou",type:"Button",x:170,y:34,width:78,height:27,
						children:
						[
							{name:"myScaleImage",type:"ScaleImage",x:0,y:0,width:78,height:27,top:4,right:4,bottom:4,left:4,normal:{link:"RankPanel_mignren",x:0,y:0,width:78,height:27}}
						]
					},
					{name:"msgScroll",type:"ScrollBar",x:110,y:131,width:17,height:321,
						children:
						[
							{name:"track",type:"Button",x:0,y:13,width:16,height:294,
								children:
								[
									{name:"track",type:"Image",x:0,y:0,width:16,height:294,normal:{link:"RankPanel_track",x:0,y:0,width:16,height:294}}
								]
							},
							{name:"thumb",type:"Button",x:2,y:18,width:13,height:35,
								children:
								[
									{name:"back",type:"ScaleImage",x:0,y:0,width:13,height:35,top:2,right:2,bottom:2,left:2,normal:{link:"RankPanel_rwzuizong5xx",x:0,y:0,width:13,height:35},over:{link:"RankPanel_rwzuizong5xxx",x:0,y:0,width:13,height:35}}
								]
							},
							{name:"arrowUp",type:"Button",x:1,y:0,width:16,height:15,
								children:
								[
									{name:"myImage",type:"Image",x:0,y:0,width:16,height:15,normal:{link:"RankPanel_rwzuizong4",x:0,y:0,width:16,height:15},over:{link:"RankPanel_rwzuizong4x",x:0,y:0,width:16,height:15}}
								]
							},
							{name:"arrowDown",type:"Button",x:1,y:306,width:16,height:15,
								children:
								[
									{name:"myImage",type:"Image",x:0,y:0,width:16,height:15,normal:{link:"RankPanel_rwzuizong18",x:0,y:0,width:16,height:15},over:{link:"RankPanel_rwzuizong18x",x:0,y:0,width:16,height:15}}
								]
							}
						]
					}
				]
			};
	}
}